//
//  SearchWikipediaInteractorInteractor.swift
//  WikipediaSearchApp
//
//  Created by DEEP PRADHAN on 18/10/18.
//  Copyright (c) 2018 DEEP PRADHAN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchWikipediaInteractorBusinessLogic {
    func queryWikipedia(request: SearchWikipediaModel.FetchResponse.Request)
}

protocol SearchWikipediaInteractorDataStore {
    
}

class SearchWikipediaInteractor: SearchWikipediaInteractorBusinessLogic, SearchWikipediaInteractorDataStore {
    var presenter: SearchWikipediaInteractorPresentationLogic?
    var worker: SearchWikipediaInteractorWorker?
    
    // MARK: Do queryWikipedia
    
    func queryWikipedia(request: SearchWikipediaModel.FetchResponse.Request)
    {
        worker = SearchWikipediaInteractorWorker()
        var searchedResultInfoReceived: [SearchedInformation] = []
        worker?.fetchWikipediaResult(searchWikipediaWithString: request.search, completionHandler: { [weak self] (result: FetchDataResult) in
            guard let strongSelf = self else {return}
            switch result {
            case .success(result: let fetchedData):
                searchedResultInfoReceived = fetchedData
                let response = SearchWikipediaModel.ShowSearchResult.Response.init(searchResult: searchedResultInfoReceived)
                strongSelf.presenter?.presentSearchResults(response: response)
            case .failure(let error):
                let errorMsg = error
            }
        })
    }
}
