//
//  SearchWikipediaPresenterPresenter.swift
//  WikipediaSearchApp
//
//  Created by DEEP PRADHAN on 18/10/18.
//  Copyright (c) 2018 DEEP PRADHAN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchWikipediaInteractorPresentationLogic
{
  func presentSearchResults(response: SearchWikipediaModel.ShowSearchResult.Response)
}

class SearchWikipediaPresenter: SearchWikipediaInteractorPresentationLogic
{
  weak var viewController: SearchWikipediaViewControllerDisplayLogic?
  
  // MARK: Do presentSearchResults
  
  func presentSearchResults(response: SearchWikipediaModel.ShowSearchResult.Response)
  {
    let viewModel = SearchWikipediaModel.ShowSearchResult.ViewModel.init(showResult: response.searchResult)
    viewController?.displaySearchResult(viewModel: viewModel)
  }
}
