//
//  SearchWikipediaModelModels.swift
//  WikipediaSearchApp
//
//  Created by DEEP PRADHAN on 18/10/18.
//  Copyright (c) 2018 DEEP PRADHAN. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchWikipediaModel
{
    // MARK: Use cases
    
    enum FetchResponse
    {
        struct Request
        {
            let search: String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum ShowSearchResult {
        struct Request
        {
        }
        struct Response
        {
            var searchResult: [SearchedInformation]
        }
        struct ViewModel
        {
             var showResult: [SearchedInformation]
        }
    }
}
